c = open('c:/semester 2/Web UAS/index.html', 'r', encoding='utf-8').read()
p = c.find('id="persona"')
d = c.find('id="define"')
a = c.find('id="empathize"')
print(f'Persona pos: {p}')
print(f'Define pos:  {d}')
print(f'Affinity pos: {a}')
print(f'Order: Persona -> Define -> Affinity = {p < d < a}')
print(f'Define section found: {"Define Problem" in c}')
print(f'Interview placeholders intact: {c.count("[Isi Pertanyaan")}')
